import category1 from "../../assets/img/p-category/category1.jpg";
import category2 from "../../assets/img/p-category/category2.jpg";
import category3 from "../../assets/img/p-category/category3.jpg";

export const generalInfoData = {
  pageTitle: "Our knowledge base",
  pageSubTitle: "Read Our current and prior updates.",

  categories: [
    {
      date: "Nov 16, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "How to Sell the Bitcoin Top and Lock in Gains in this Bull Cycle",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: '', 
    },
    {
      date: "Nov 16, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "6 Signs That Tell You When to Sell Your Crypto tokens, lock in massive gains, and avoid Massive Bear Market drawdowns",
      subheader: "Crypto is a fast-moving landscape",
      time: "2 min read",
      photo: category1,
    },
    {
      date: "Nov 16, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "5 Quick Red Flags You Must Avoid to Protect Your Funds From Cryptocurrency Scammers",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: category2,
    },
    {
      date: "Nov 15, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "How to be a Balanced Crypto Investor",
      subheader: "Investing in cryptocurrencies has been incredibly rewarding in the last ten years",
      time: "2 min read",
      photo: category3,
    },
    {
      date: "Nov 15, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "5 Quick Red Flags You Must Avoid to Protect Your Funds From Cryptocurrency Scammers",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: category2,
    },
    {
      date: "Nov 14, 2020",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "6 Signs That Tell You When to Sell Your Crypto tokens, lock in massive gains, and avoid Massive Bear Market drawdowns",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: category3,
    },
    {
      date: "Nov 15, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "How to be a Balanced Crypto Investor",
      subheader: "Investing in cryptocurrencies has been incredibly rewarding in the last ten years",
      time: "2 min read",
      photo: category1,
    },
    {
      date: "Nov 15, 2021",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "5 Quick Red Flags You Must Avoid to Protect Your Funds From Cryptocurrency Scammers",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: category3,
    },
    {
      date: "Nov 14, 2020",
      author: "Roselyne Wanjiru",
      category: "General Information",
      header: "6 Signs That Tell You When to Sell Your Crypto tokens, lock in massive gains, and avoid Massive Bear Market drawdowns",
      subheader: "Cryptocurrency scammers are bold enough to keep coming after your funds",
      time: "2 min read",
      photo: '',
    },
  ],
};
